version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/localzet/xray-editor"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "prettier"